language: python
python: 2.7
vm:
  size: 2x-large
env:
  - TOX_ENV=py27-dj16
  - TOX_ENV=py27-dj17
  - TOX_ENV=py27-dj18
before_install:
  - nproc
  - free -hm
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
